version: '3.1'

services:
  upload-file:
    image: "upload-file"
    container_name: upload-file
    ports:
      - "9000:9000"
    volumes:
      - "./data/conf:/data/conf"
    networks:
      - default-net

networks:
  default-net:
    external:
      name: dev_bridge
