server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:6000
    timeout: 1s

data:
  redis:
    network: tcp
    addr: 0.0.0.0:6379
    password: ""
    read_timeout: 0.2s
    write_timeout: 0.2s
  object_storage:
    domain: 0.0.0.0:9000
    access_key_id: miniotest
    secret_access_key: miniotest
    location: dev
    secure: false

upload_file:
  secret_key: "test"
